language: java
sudo: true
dist: trusty
jdk: oraclejdk8
before_install:
  - cd GroupProject
  - chmod +x mvnw
deploy:
  provider: heroku
  api-key:
    secure: $HEROKU_API_KEY
  app: sysc-4806-project-2021
